In [ ]:
# Inicializa listas vacías para guardar los datos
nombre = []
identificacion = []
direccion = []

# Define el número de registros que se van a ingresar
tamaño = 3

# Bucle para pedir datos 'tamaño' veces
for i in range(tamaño):
    # Solicita el nombre al usuario
    nombre_input = input("Nombre: ")
    # Solicita la identificación al usuario
    identificacion_input = input("Identificación: ")
    # Solicita la dirección al usuario
    direccion_input = input("Direccion: ")

    # Agrega los datos ingresados a las listas correspondientes
    nombre.append(nombre_input)
    identificacion.append(identificacion_input)
    direccion.append(direccion_input)

# Imprime las listas con los datos almacenados
print("Nombres:", nombre)
print("Identificaciones:", identificacion)
print("Direcciones:", direccion)

In [ ]:
# Importa la biblioteca numpy con el alias np
import numpy as np

# Define una lista de números
lst = [10, 20, 30, 40, 50]

# Convierte la lista en un array de numpy (vector)
vct = np.array(lst)

# Se repite la conversión (esta línea es redundante y puede omitirse)
vct = np.array(lst)

# Imprime el texto "listooo:"
print("listooo:")

# Imprime el array numpy creado
print(vct)

listooo:
[10 20 30 40 50]


In [ ]:
# Importa la biblioteca numpy con el alias np
import numpy as np

# Define una lista de nombres
lst = ["isabel", "camilo", "Sebastian"]

# Convierte la lista en un array de numpy (vector)
nm = np.array(lst)

# Se repite la conversión (esta línea es redundante y puede omitirse)
nm = np.array(lst)

# Imprime el texto "Nombres:"
print("Nombres:")

# Imprime el array numpy con los nombres
print(nm)

Nombres:
['isabel' 'camilo' 'Sebastian']


In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define una lista de frutas
lst = ["pera", "manzana", "durazno", "sandia"]

# Convierte la lista en un array numpy
frt = np.array(lst)

# La siguiente línea es redundante y puede eliminarse
frt = np.array(lst)

# Imprime el texto "Frutas:"
print("Frutas:")

# Imprime el array numpy con las frutas
print(frt)

Frutras:
['pera' 'manzana' 'durazno' 'sandia']


In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define una lista de listas con números
lst = [[2], [4], [6], [10]]

# Define una lista de listas con nombres de frutas
lstF = [["peras"], ["manzanas"], ["fresas"]]

# Define una lista de listas con nombres de personas
lstN = [["Isabel"], ["Lorena"], ["Nicol"]]

# Convierte las listas en arrays numpy (matrices columna)
vct = np.array(lst)
vctF = np.array(lstF)
vctN = np.array(lstN)

# Imprime el título "Números:" y el array de números
print("Números:")
print(vct)

# Imprime el título "Frutas:" y el array de frutas
print("Frutas:")
print(vctF)

# Imprime el título "Nombres:" y el array de nombres
print("Nombres:")
print(vctN)

Números:
[[ 2]
 [ 4]
 [ 6]
 [10]]
Frutas:
[['peras']
 ['manzanas']
 ['fresas']]
Nombres:
[['Isabel']
 ['Lorena']
 ['Nicol']]


In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define dos listas de números
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 2, 3, 4, 5]

# Convierte las listas en arrays numpy para operaciones vectoriales
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime el primer vector
print("resultado vector 1:")
print(vct1)

# Imprime el segundo vector
print("resultado vector 2:")
print(vct2)

# Suma elemento a elemento los dos vectores
vct_add = vct1 + vct2

# Imprime el resultado de la suma
print(vct_add)

resultado vector 1:
[10 20 30 40 50]
resultado vector 2:
[1 2 3 4 5]
[11 22 33 44 55]


In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define dos listas de números
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 2, 3, 4, 5]

# Convierte las listas en arrays numpy para operaciones vectoriales
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime el primer vector
print("resultado vector 1:")
print(vct1)

# Imprime el segundo vector
print("resultado vector 2:")
print(vct2)

# Suma elemento a elemento los dos vectores
vct_add = vct1 + vct2

# Imprime el resultado de la suma
print(vct_add)

resultado vector 1:
[10 20 30 40 50]
resultado vector 2:
[1 2 3 4 5 6 7]


ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define dos listas de números
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 2, 3, 4, 5]

# Convierte las listas en arrays numpy para operaciones vectoriales
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime el primer vector
print("resultado vector 1:")
print(vct1)

# Imprime el segundo vector
print("resultado vector 2:")
print(vct2)

# Resta elemento a elemento el segundo vector del primero
vct_add = vct1 - vct2

# Imprime el resultado de la resta
print(vct_add)

resultado vector 1:
[10 20 30 40 50]
resultado vector 2:
[1 2 3 4 5]
[ 9 18 27 36 45]


In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define dos listas de números
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 2, 3, 4, 5]

# Convierte las listas en arrays numpy para facilitar operaciones vectoriales
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime un encabezado para las operaciones
print("operaciones:")

# Suma elemento a elemento
print("Suma:")
vctD = vct1 + vct2
print(vctD)

# Resta elemento a elemento
print("Resta:")
vctD = vct1 - vct2
print(vctD)

# Multiplicación elemento a elemento
print("Multiplicacion:")
vctM = vct1 * vct2
print(vctM)

# División elemento a elemento
print("Division:")
vctD = vct1 / vct2
print(vctD)

operaciones:
Suma:
[11 22 33 44 55]
Resta:
[ 9 18 27 36 45]
Multiplicacion:
[ 10  40  90 160 250]
Division:
[10. 10. 10. 10. 10.]


In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define dos listas de números
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 1, 1, 1, 1]

# Convierte las listas en arrays numpy para operaciones vectoriales
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime el primer vector
print("resultado vector 1:")
print(vct1)

# Imprime el segundo vector
print("resultado vector 2:")
print(vct2)

# Calcula el producto punto (dot product) de los dos vectores
vct_dot = vct1.dot(vct2)

# Imprime el resultado del producto punto
print(vct_dot)

resultado vector 1:
[10 20 30 40 50]
resultado vector 2:
[1 1 1 1 1]
150


In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define dos listas de números
lst1 = [10, 20, 30, 40, 50]
lst2 = [2, 2, 2, 2, 2]

# Convierte las listas en arrays numpy para operaciones vectoriales
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime el primer vector
print("resultado vector 1:")
print(vct1)

# Imprime el segundo vector
print("resultado vector 2:")
print(vct2)

# Calcula el producto punto (dot product) de los dos vectores
vct_dot = vct1.dot(vct2)

# Imprime el resultado del producto punto
print(vct_dot)

resultado vector 1:
[10 20 30 40 50]
resultado vector 2:
[2 2 2 2 2]
300
