In [ ]:
# Se crean tres listas vacías para almacenar los datos de cada persona
nombre = []          # Lista para nombres
identificacion = []  # Lista para identificaciones
direccion = []       # Lista para direcciones

# Se define cuántas personas se van a registrar
tamaño = 3

# Bucle que se repite 'tamaño' veces para capturar los datos de cada persona
for i in range(tamaño):
    # Solicita el nombre del usuario
    nombre_input = input("Nombre: ")

    # Solicita la identificación del usuario
    identificacion_input = input("Identificación: ")

    # Solicita la dirección del usuario
    direccion_input = input("Dirección: ")

    # Agrega los datos ingresados a sus respectivas listas
    nombre.append(nombre_input)
    identificacion.append(identificacion_input)
    direccion.append(direccion_input)

# Muestra todas las listas con los datos ingresados
print("Nombres:", nombre)
print("Identificaciones:", identificacion)
print("Direcciones:", direccion)


Nombre: dfghjkl
Identificación: 23456789
Direccion: sdfgkl
Nombre: sdfghjk
Identificación: 456789
Direccion: dfghjk
Nombre: fghjkl
Identificación: 3456789
Direccion: dfghjkl
Nombres: ['dfghjkl', 'sdfghjk', 'fghjkl']
Identificaciones: ['23456789', '456789', '3456789']
Direcciones: ['sdfgkl', 'dfghjk', 'dfghjkl']


In [ ]:
# Importa el módulo numpy, renombrado como 'np' para usarlo más fácilmente
import numpy as np

# Se define una lista de números enteros
lst = [10, 20, 30, 40, 50]

# Se convierte la lista a un array de NumPy
vct = np.array(lst)  # Esto permite trabajar con operaciones vectorizadas

# Imprime un encabezado informativo
print("Listooo:")

# Imprime el array convertido desde la lista
print(vct)


listooo:
[10 20 30 40 50]


In [ ]:
# Importa la librería numpy y la renombra como np para facilitar su uso
import numpy as np

# Define una lista de nombres (strings)
lst = ["isabel", "camilo", "Sebastian"]

# Convierte la lista en un array de numpy (vector de strings)
nm = np.array(lst)

# La segunda conversión es redundante, por eso se elimina:
# nm = np.array(lst)

# Imprime un encabezado
print("Nombres:")

# Imprime el array de nombres
print(nm)

Nombres:
['isabel' 'camilo' 'Sebastian']


In [ ]:
# Importa la librería numpy como np
import numpy as np

# Lista de frutas
lst = ["pera", "manzana", "durazno", "sandia"]

# Convierte la lista en un array de numpy
frt = np.array(lst)

# Nota: La siguiente línea es redundante y se elimina
# frt = np.array(lst)

# Imprime un título para la lista de frutas
print("Frutas:")

# Imprime el array con las frutas
print(frt)


Frutras:
['pera' 'manzana' 'durazno' 'sandia']


In [ ]:
# Importa la biblioteca numpy como np
import numpy as np

# Lista de listas con números (cada número está en una lista)
lst = [[2], [4], [6], [10]]

# Lista de listas con frutas (cada fruta está en una lista)
lstF = [["peras"], ["manzanas"], ["fresas"]]

# Lista de listas con nombres (cada nombre está en una lista)
lstN = [["Isabel"], ["Lorena"], ["Nicol"]]

# Convierte cada lista en un array numpy
vct = np.array(lst)
vctF = np.array(lstF)
vctN = np.array(lstN)

# Imprime los arrays con un título para cada uno
print("Números:")
print(vct)

print("Frutas:")
print(vctF)

print("Nombres:")
print(vctN)

Números:
[[ 2]
 [ 4]
 [ 6]
 [10]]
Frutas:
[['peras']
 ['manzanas']
 ['fresas']]
Nombres:
[['Isabel']
 ['Lorena']
 ['Nicol']]


In [ ]:
# Importa la biblioteca numpy con el alias np
import numpy as np

# Define dos listas de números
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 2, 3, 4, 5]

# Convierte las listas en arrays de numpy
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime los arrays originales
print("Resultado vector 1:")
print(vct1)
print("Resultado vector 2:")
print(vct2)

# Suma elemento a elemento ambos arrays
vct_add = vct1 + vct2

# Imprime el resultado de la suma
print("Suma de los dos vectores:")
print(vct_add)


resultado vector 1:
[10 20 30 40 50]
resultado vector 2:
[1 2 3 4 5]
[11 22 33 44 55]


In [ ]:
# Importa la biblioteca numpy con el alias np
import numpy as np

# Define dos listas con diferente cantidad de elementos
lst1 = [10, 20, 30, 40, 50]        # Longitud 5
lst2 = [1, 2, 3, 4, 5, 6, 7]       # Longitud 7

# Convierte las listas en arrays numpy
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime ambos vectores
print("Resultado vector 1:")
print(vct1)
print("Resultado vector 2:")
print(vct2)

# Intenta sumar ambos vectores (esto producirá un error)
vct_add = vct1 + vct2

# Imprime el resultado de la suma
print(vct_add)

resultado vector 1:
[10 20 30 40 50]
resultado vector 2:
[1 2 3 4 5 6 7]


ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [ ]:
# Importa la biblioteca numpy y la renombra como np para facilitar su uso
import numpy as np

# Define dos listas con números
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 2, 3, 4, 5]

# Convierte las listas en arrays de numpy
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime el primer vector
print("Resultado vector 1:")
print(vct1)

# Imprime el segundo vector
print("Resultado vector 2:")
print(vct2)

# Resta los dos vectores elemento por elemento
vct_add = vct1 - vct2

# Imprime el resultado de la resta
print(vct_add)

resultado vector 1:
[10 20 30 40 50]
resultado vector 2:
[1 2 3 4 5]
[ 9 18 27 36 45]


In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define dos listas de números
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 2, 3, 4, 5]

# Convierte las listas en arrays numpy para operar vectorialmente
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime un encabezado general para las operaciones
print("Operaciones:")

# Suma elemento a elemento
print("Suma:")
vctD = vct1 + vct2
print(vctD)

# Resta elemento a elemento
print("Resta:")
vctD = vct1 - vct2
print(vctD)

# Multiplicación elemento a elemento
print("Multiplicación:")
vctM = vct1 * vct2
print(vctM)

# División elemento a elemento (resultado en float)
print("División:")
vctD = vct1 / vct2
print(vctD)

operaciones:
Suma:
[11 22 33 44 55]
Resta:
[ 9 18 27 36 45]
Multiplicacion:
[ 10  40  90 160 250]
Division:
[10. 10. 10. 10. 10.]


In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define dos listas de números
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 1, 1, 1, 1]

# Convierte las listas en arrays numpy para operaciones vectoriales
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime el primer vector
print("Resultado vector 1:")
print(vct1)

# Imprime el segundo vector
print("Resultado vector 2:")
print(vct2)

# Calcula el producto punto (dot product) entre los dos vectores
vct_dot = vct1.dot(vct2)

# Imprime el resultado del producto punto
print("Producto punto de los vectores:")
print(vct_dot)

resultado vector 1:
[10 20 30 40 50]
resultado vector 2:
[1 1 1 1 1]
150


In [ ]:
# Importa la biblioteca numpy con alias np
import numpy as np

# Define dos listas de números
lst1 = [10, 20, 30, 40, 50]
lst2 = [2, 2, 2, 2, 2]

# Convierte las listas en arrays numpy para operaciones vectoriales
vct1 = np.array(lst1)
vct2 = np.array(lst2)

# Imprime el primer vector
print("Resultado vector 1:")
print(vct1)

# Imprime el segundo vector
print("Resultado vector 2:")
print(vct2)

# Calcula el producto punto (dot product) entre los dos vectores
vct_dot = vct1.dot(vct2)

# Imprime el resultado del producto punto
print("Producto punto de los vectores:")
print(vct_dot)

resultado vector 1:
[10 20 30 40 50]
resultado vector 2:
[2 2 2 2 2]
300
